spring:
  data:
    mongodb:
      username: root
      database: mydatabase
      password: secret
      port: '27017'
      host: localhost
  rabbitmq:
    username: myuser
    password: secret
    host: localhost
    port: '5672'


sm:
  rabbitExchangeName: testE
  rabbitRoutineKey: testR


eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
