spring:
  data:
    mongodb:
      username: root
      database: mydatabase
      password: secret
      port: '27017'
      host: localhost
  rabbitmq:
    username: myuser
    password: secret
    host: localhost
    port: '5672'
